function varargout=readsac(filename,plotornot,osd)
% [SeisData,HdrData,tnu,pobj]=READSAC(filename,plotornot,osd)
% [SeisData,HdrData,tnu,pobj]=READSAC(filename,1)
% [SeisData,HdrData,tnu,pobj]=READSAC(filename,1,'l')
% [SeisData,HdrData,tnu,pobj]=READSAC(filename,1,'b')
% READSAC(...)
%
% Reads SAC-formatted data (and makes a plot)
%
% Last modified by fjsimons@alum.mit.edu, 2/8/2003
%
% 'b' for data saved on Solaris read into Linux
% 'l' for data saved on Linux read into Linux

defval('plotornot',0)
defval('osd',osdep) %jpa WARNING: did not work on my laptop 28-Jan-2005
%defval('osd','l')

fid=fopen(filename,'r',osd);
if fid==-1
  error([ 'File ',filename,' does not exist in current path ',pwd])
end
HdrF=fread(fid,70,'float32');
HdrN=fread(fid,15,'int32');
HdrI=fread(fid,20,'int32');
HdrL=fread(fid,5,'int32');
HdrK=str2mat(fread(fid,[8 24],'char'))';
SeisData=fread(fid,HdrN(10),'float32');
fclose(fid);

HdrData=struct(...
  'NPTS',HdrN(10),...
  'B',HdrF(6),...
  'E',HdrF(7),...
  'T0',HdrF(11),...
  'T1',HdrF(12),...
  'DELTA',HdrF(1),...
  'SCALE',HdrF(4),...
  'STLA',HdrF(32),...   
  'STLO',HdrF(33),...
  'STEL',HdrF(34),...
  'STDP',HdrF(35),...
  'EVLA',HdrF(36),...
  'EVLO',HdrF(37),...
  'EVEL',HdrF(38),...
  'EVDP',HdrF(39),...
  'MAG',HdrF(40),...
  'NZYEAR',HdrN(1),...
  'NZJDAY',HdrN(2),...
  'NZHOUR',HdrN(3),...
  'NZMIN',HdrN(4),...
  'NZSEC',HdrN(5),...
  'NZMSEC',HdrN(6),...
  'NVHDR',HdrN(7),...
  'KINST',deblank(HdrK(24,:)),...
  'KCMPNM',leadblnk(deblank(HdrK(21,:))),...
  'KSTNM',deblank(HdrK(1,:)),...
  'KUSER0',deblank(HdrK(18,:)));

if plotornot==1
  pobj=plot(linspace(HdrData.B,HdrData.E,HdrData.NPTS),SeisData);
  filename(find(abs(filename)==95))='-';
%  tnu=title(suf(filename,'/'));
  tnu=title(filename); % JPA replaced previous line, missing SUF
  axis tight
  xlabel([ 'Time (s)'])
else
  tnu=0;
  pobj=0;
end

nam={'SeisData' 'HdrData' 'tnu' 'pobj'};
for index=1:nargout
  varargout{index}=eval(nam{index});
end
